name: on-pr-use-head-ref

on:
  # Context: we don't trigger builds on `pull_request:synchronize` if there's a merge conflict.
  # Including the `push` event should guarantee that a build is run for **any** commit pushed to the repository.
  push: 
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - env:
        GH_REF: ${{ github.ref }}
        GH_HEAD_REF: ${{ github.head_ref }}
      run: |
        echo $GH_REF
        echo $GH_HEAD_REF

    - name: Checkout at the PR's compare branch's HEAD ref
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
